[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Rota API -> Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback — qualquer rota serve o index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
